### ISSUE TITLE
pin list gives 500

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-queue-pinservice#12]
```json
{
	"error": "ResponseValidationError: Response 202 is not defined in the OAS Document for GET /pins"
}
```

In the IPFS GUI (Companion/Desktop):
![image](https://user-images.githubusercontent.com/22742/197749395-c6b483e2-3cfb-4c5d-953a-81357fe2dd4b.png)

Should return empty list, so we're following the spec. Example:

```json
{
"count": 0,
"results": []
}
```

**Comment by femans** [comment]
Solved with https://github.com/ipfs-search/ipfs-search-queue-pinservice/commit/4e7ade4b994b78abb9e27f68c128f6c29349d137
