### ISSUE TITLE
README missing 'Getting started'

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-queue-pinservice#3]
Similar to:
* https://github.com/ipfs-search/ipfs-search-queue-pinservice#testing
* https://github.com/ipfs-search/nyats/tree/main/packages/server#usage
* https://github.com/ipfs-search/ipfs-search-api#server

**Comment by femans** [comment]
https://github.com/ipfs-search/ipfs-search-queue-pinservice/issues/5 will be solved by this; to start the service, it needs to be built first.

**Comment by femans** [comment]
https://github.com/ipfs-search/ipfs-search-queue-pinservice#getting-started
