### ISSUE TITLE
Security middleware disabled: why?

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-queue-pinservice#8]
Is there a good reason? If so, perhaps we should have a comment explaining this. If not, let's please enable it!

https://github.com/ipfs-search/ipfs-search-queue-pinservice/blob/main/src/server.ts#L22

**Comment by femans** [comment]
https://oas-tools.github.io/docs/features/security

We discussed that for now we will run it without authentication.
